### ISSUE TITLE
Int32 Column Metadata read as Int96

### ISSUE THREAD

**Issue by virajp691** [RyanEder/clearParquet#19]
### Description
As part of #18 unit test I get the following error. Stacktrace included. Int32 column metadata is read/detected as Int96.

### Error:
```
clearParquet/test/unittest.cpp:224: FAILED:
due to unexpected exception with message:
  Unsupported type: INT96
 ```
 
### StackTrace
```
#0  clearParquet::RecordBatch::ParseBuffer (this=0x7b6080, type=clearParquet::Type::INT96, cBuffer=0x7b0a40 "", numValues=0, name=..., dataSize=0) at /home/viraj/external/clearParquet/core/ParquetRecordBatch.hpp:101
#1  0x0000000000423113 in clearParquet::ParquetFileReader::ReadData (this=0x7d4040, type=clearParquet::Type::INT96, numValues=0, dataSize=0, offset=1, batch=..., name=...) at /home/viraj/external/clearParquet/core/ParquetFileReader.hpp:284
#2  0x0000000000423324 in clearParquet::ParquetFileReader::ReadIntoBatch (this=0x7d4040) at /home/viraj/external/clearParquet/core/ParquetFileReader.hpp:299
#3  0x0000000000422926 in clearParquet::ParquetFileReader::ReadFileMetadata (this=0x7d4040) at /home/viraj/external/clearParquet/core/ParquetFileReader.hpp:237
#4  0x000000000042162d in clearParquet::ParquetFileReader::Open (filename=...) at /home/viraj/external/clearParquet/core/ParquetFileReader.hpp:37
#5  0x000000000040e3c8 in CATCH2_INTERNAL_TEST_32 () at /home/viraj/external/clearParquet/test/unittest.cpp:242
#6  0x00000000004b4130 in Catch::(anonymous namespace)::TestInvokerAsFunction::invoke (this=0x7ae760) at src/catch2/internal/catch_test_registry.cpp:58
#7  0x000000000049fd4d in Catch::TestCaseHandle::invoke (this=0x7d8340) at src/catch2/../catch2/catch_test_case_info.hpp:115
#8  0x000000000049ed61 in Catch::RunContext::invokeActiveTestCase (this=0x7fffffffd5f0) at src/catch2/internal/catch_run_context.cpp:552
#9  0x000000000049eacd in Catch::RunContext::runCurrentTest (this=0x7fffffffd5f0, redirectedCout=..., redirectedCerr=...) at src/catch2/internal/catch_run_context.cpp:515
#10 0x000000000049d321 in Catch::RunContext::runTest (this=0x7fffffffd5f0, testCase=...) at src/catch2/internal/catch_run_context.cpp:239
#11 0x000000000045420a in Catch::(anonymous namespace)::TestGroup::execute (this=0x7fffffffd5e0) at src/catch2/catch_session.cpp:111
#12 0x0000000000455463 in Catch::Session::runInternal (this=0x7fffffffd900) at src/catch2/catch_session.cpp:333
#13 0x0000000000455025 in Catch::Session::run (this=0x7fffffffd900) at src/catch2/catch_session.cpp:264
#14 0x0000000000453771 in Catch::Session::run<char> (this=0x7fffffffd900, argc=2, argv=0x7fffffffdb68) at src/catch2/../catch2/catch_session.hpp:41
#15 0x00000000004536b5 in main (argc=2, argv=0x7fffffffdb68) at src/catch2/internal/catch_main.cpp:36
```

**Comment by RyanEder** [comment]
Fixed in latest main.
